In [1]:
import numpy as np

In [8]:
A = np.array([[0, 1, -1], [-1, 0, 1], [-1, 1, 0]])
columns = [0, 2]
rows = [1, 2]
solve_indifference(A, rows, columns)

array([ 1., -0.,  0.])

In [31]:
def solve_indifference(A, rows=None, columns=None):
    """
    Solve the indifference for a payoff matrix assuming support for the strategies given by columns
    
    Finds vector of probabilities that makes player indifferent between rows. 
    (So finds probability vector for corresponding column player)
    """
    M = (A[np.array(rows)] - np.roll(A[np.array(rows)], 1, axis=0))[:-1]  # Ensure differences between pairs of pure strategies are the same
    M = np.append(M, [[1 for _ in M.T]], axis=0)   # Ensure have probability vector
    zero_columns = set(range(A.shape[1])) - set(columns)  # Columns that must be played with prob 0
    b = np.append(np.zeros(len(M) - 1), [1] + [0 for _ in zero_columns])
   
    if zero_columns != set():
        M = np.append(M, [[int(i == j) for i, col in enumerate(M.T)] for j in zero_columns], axis=0)
    
    try:
        prob = np.linalg.solve(M, b)
        assert all(prob >= 0), "Not a probability vector (non positive values)"
        return prob
    except np.linalg.linalg.LinAlgError:
        return None

In [33]:
p = solve_indifference(np.array([[-1, 1, -1], [1, -1, 1], [-1, 0, 0]]), rows=(0, 1), columns=(0, 1))
p

array([ 0.5,  0.5,  0. ])

In [14]:
p = solve_indifference(np.array([[0, 1, -1], [1, 0, 1], [-1, 1, 0]]), rows=[0, 1, 2], columns=[0, 1, 2])
p

array([ 0.2,  0.6,  0.2])

In [38]:
A = np.array([[2, 1], [0, 2]])
B = np.array([[2, 0], [1, 2]])
rows, columns = [0], [0]
p1 = solve_indifference(A, rows, columns)
p2 = solve_indifference(B.T, columns, rows)
p1, p2

(array([ 1.,  0.]), array([ 1.,  0.]))

In [39]:
A = np.array([[2, 1], [0, 2]])
B = np.array([[2, 0], [1, 2]])
rows, columns = [0], [1]
p1 = solve_indifference(A, rows, columns)
p2 = solve_indifference(B.T, columns, rows)
p1, p2

(array([ 0.,  1.]), array([ 1.,  0.]))

In [40]:
A = np.array([[2, 1], [0, 2]])
B = np.array([[2, 0], [1, 2]])
rows, columns = [0], [1]
p1 = solve_indifference(A, rows, columns)
p2 = solve_indifference(B.T, columns, rows)
p1, p2

(array([ 1.,  0.]), array([ 0.,  1.]))

In [42]:
A = np.array([[2, 1], [0, 2]])
B = np.array([[2, 0], [1, 2]])
rows, columns = [1], [1]
p1 = solve_indifference(A, rows, columns)
p2 = solve_indifference(B.T, columns, rows)
p1, p2

(array([ 0.,  1.]), array([ 0.,  1.]))

In [43]:
A = np.array([[2, 1], [0, 2]])
B = np.array([[2, 0], [1, 2]])
rows, columns = [0, 1], [0, 1]
p1 = solve_indifference(A, rows, columns)
p2 = solve_indifference(B.T, columns, rows)
p1, p2

(array([ 0.33333333,  0.66666667]), array([ 0.33333333,  0.66666667]))