> Obtain the full game representations $(A, B)$ for the zero sum games with row play payoff matrix given by:

   1. $A =\begin{pmatrix}1 & 3\\ -1 & 4\end{pmatrix}\qquad B =\begin{pmatrix}-1 & -3\\ 1 & -4\end{pmatrix}$

In [12]:
import nashpy as nash
import numpy as np

A = np.array(((1, 3), (-1, 4)))
game = nash.Game(A)
game

Zero sum game with payoff matrices:

Row player:
[[ 1  3]
 [-1  4]]

Column player:
[[-1 -3]
 [ 1 -4]]

   2. $A =\begin{pmatrix}1 & -2\\ -1 & 2\end{pmatrix}\qquad B =\begin{pmatrix}-1 & 2\\ 1 & -2\end{pmatrix}$

In [13]:
A = np.array(((1, -2), (-1, 2)))
B = np.array(((-1, 2), (1, -2)))
game = nash.Game(A, B)
game

Zero sum game with payoff matrices:

Row player:
[[ 1 -2]
 [-1  2]]

Column player:
[[-1  2]
 [ 1 -2]]

   3. $A =\begin{pmatrix}1 & -2 & 4\\ 2 & -1 & 2\\ 7 & -7 & 6\end{pmatrix}\qquad B =\begin{pmatrix}-1 & 2 & -4\\ -2 & 1 & -2\\ -7 & 7 & -6\end{pmatrix}$

In [14]:
A = np.array(((1, -2, 4), (2, -1, 2), (7, -7, 6)))
B = np.array(((-1, 2, -4), (-2, 1, -2), (-7, 7, -6)))
game = nash.Game(A, B)
game

Zero sum game with payoff matrices:

Row player:
[[ 1 -2  4]
 [ 2 -1  2]
 [ 7 -7  6]]

Column player:
[[-1  2 -4]
 [-2  1 -2]
 [-7  7 -6]]

> `3.` Consider the game described as follows:

   > An airline loses two suitcases belonging to two different travelers. Both suitcases have the same value. An airline manager tasked to settle the claims of both travelers explains that the airline is liable for a maximum of £5 per suitcase. 

   > To determine an honest appraised value of the suitcases, the manager separates both travelers and asks them to write down the amount of their value at no less than £2 and no larger than £5 (to the single dollar):
   > - If both write down the same number, that number as the true dollar value of both suitcases and reimburse both travelers that amount. 
   > - However, if one writes down a smaller number than the other, this smaller number will be taken as the true dollar value, and both travelers will receive that amount along with a bonus/malus: £2 extra will be paid to the traveler who wrote down the lower value and a £2 deduction will be taken from the person who wrote down the higher amount. 
   
   > Represent this as a Normal Form Game.
   
   
$$
A = \begin{pmatrix}
2 & 4 & 4 & 4\\
0 & 3 & 5 & 5\\
0 & 1 & 4 & 6\\
0 & 1 & 2 & 5
\end{pmatrix}
\qquad
B = \begin{pmatrix}
2 & 0 & 0 & 0\\
4 & 3 & 1 & 1\\
4 & 5 & 4 & 2\\
4 & 5 & 6 & 5
\end{pmatrix}
$$

In [15]:
A = np.array(((2, 4, 4, 4), (0, 3, 5, 5), (0, 1, 4, 6), (0, 1, 2,5)))
B = np.array(((2, 0, 0, 0), (4, 3, 1, 1), (4, 5, 4, 2), (4, 5, 6, 5)))
game = nash.Game(A, B)
game

Bi matrix game with payoff matrices:

Row player:
[[2 4 4 4]
 [0 3 5 5]
 [0 1 4 6]
 [0 1 2 5]]

Column player:
[[2 0 0 0]
 [4 3 1 1]
 [4 5 4 2]
 [4 5 6 5]]